s = set ()
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
n = input(" enter any number")
s.add(int(n))
print(s)